name = "Terraform Boat Bug"
author = "Kneelawk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56668b6c80e8a5975c91736d3fc8d79028595bc95275971c5278d0ec8957fc93"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.3"
